[package]
name = "pro-hunter"
version = "0.1.0"
edition = "2024"

[dependencies]
screenshots = "0.8"
ocrs = "0.11"
rten = "0.22"
image = "0.24"
anyhow = "1.0"
crossterm = "0.28"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

[profile.release]
opt-level = 3
